### ISSUE TITLE
Publish qr package

### ISSUE THREAD

**Issue by andreasKroepelin** [EpicEricEE/typst-plugins#1]
There are currently two published Typst packages for generating QR codes, to my knowledge. One is native Typst (probably not the fastest) and one calls a whole JavaScript runtime. Your implementation using Rust and wasm looks very reasonable and nicely done to me so I'd love to see it in the official package repository!

**Comment by EpicEricEE** [comment]
You're right that this package is probably more efficient than the other two, but a new package has just been created, which I think is even better suited than this. It contains many more types of codes, though it seems to lack color customization as of now:

https://github.com/typst/packages/pull/263
