### ISSUE TITLE
Equate: `\nonumber` equivalent

### ISSUE THREAD

**Issue by SolidTux** [EpicEricEE/typst-plugins#10]
It would be nice to have an in-between version of numbering every line and numbering only labels. In LaTeX, `\nonumber` exists to skip numbering a single line.

**Comment by EpicEricEE** [comment]
I added a way for you to use the label `<equate:revoke>` on a single line to skip the numbering for it, e.g.:

```typ
$ a + b \
  c + d #<equate:revoke> \
  e + f $
```

Maybe I will change the label to something more explicit in the future (such as `<no-number>`), I just wanted to keep it simple for now and reuse the label that already exists.
