### ISSUE TITLE
bad interaction with the `ilm` package

### ISSUE THREAD

**Issue by CarloLucibello** [EpicEricEE/typst-plugins#11]
Hi, 
thanks for the nice package! I discovered a bad interaction with the [ilm](https://typst.app/universe/package/ilm) package.
The following document produces a bad numbering of the equations (I'm on the the typst web app):
```typst
#import "@preview/ilm:1.1.1": ilm
#import "@preview/equate:0.2.0": equate

#show: equate.with(breakable: true, sub-numbering: true)
#set math.equation(numbering: "(1.1)")

#show: ilm.with()

= Intro

The dot product of two vectors $arrow(a)$ and $arrow(b)$ can
be calculated as shown in @dot-product.

$
  angle.l a, b angle.r &= arrow(a) dot arrow(b) \
                       &= a_1 b_1 + a_2 b_2 + ... a_n b_n \
                       &= sum_(i=1)^n a_i b_i. #<sum>
$ <dot-product>

The sum notation in @sum is a useful way to express the dot
product of two vectors.
```
<img width="508" alt="Screenshot 2024-06-19 at 09 47 21" src="https://github.com/EpicEricEE/typst-plugins/assets/7014210/96597452-cf9c-4725-9e60-4f156d969084">

**Comment by CarloLucibello** [comment]
Nevermind, if I exchange the order of the shows the problem is fixed
```typst
#show: ilm.with()

#show: equate.with(breakable: true, sub-numbering: true)
#set math.equation(numbering: "(1.1)")
```

**Comment by EpicEricEE** [comment]
It was probably just ilm overriding the set rule for the numbering of equations.
