### ISSUE TITLE
Droplet package falls down when needing more than one gyph in the dropcap

### ISSUE THREAD

**Issue by alerque** [EpicEricEE/typst-plugins#2]
It is relatively common to need more than one letter in a dropcap. That comes as a surprise to many programmers, but to book editors it's a well known problem. Frequently books get copy-edit just to avoid this problem because not all software supports it smoothly.

In my personal experience there are two frequent cases: leading quotes and trailing punctuation. Leading quotes is obvious enough in English, you don't really want a `“` to be your drop-cap, but if your first sentence starts with a quote you have to put it somewhere. The other case I more commonly see in languages like Turkish where it is not uncommon to follow a number or letter with `.` that has meaning as an ordinal and is best handled inside the dropcap itself.

You can see a sample of both cases in SILE's [sample gallery](https://sile-typesetter.org/examples/packages/):

<a href="https://sile-typesetter.org/examples/dropcaps.pdf"><img width="40%" src="https://sile-typesetter.org/examples/dropcaps.png" /></a>

I've been trying to work up something similar for Typst to put on https://polytype.dev under the [dropcap sample](https://polytype.dev/dropcaps/). I got SILE, XeLaTeX, and Groff working, but Typst isn't cooperating very nicely even with your droplet package (which otherwise seems to work pretty well).

You can see my [full attempted source code here](https://github.com/alerque/polytype/pull/6/files), but here is the relevant snippet:

```typst
#import "@preview/droplet:0.1.0": dropcap

#dropcap()[
  "No," said the package.
]
```

Is there a way this package can be used to catch a variable number of characters and not trip up on non letter characters? I did notice it works fine with some other punctuation besides a double quote, but as it can't catch two characters yet just adding double quotes to the list of acceptable characters won't quite cut the mustard.

**Comment by EpicEricEE** [comment]
I can see how that would be useful. I don't know if setting the amount of characters is the way to go here, or if it makes more sense to add an optional argument for the content of the drop-cap (as in `#dropcap["N][o," said the package]`, similar to lettrine) and fall back to the first character if only one positional argument is provided.

Also, you can probably achieve what you want with the `transform` argument, though it's arguably not the prettiest way:
```typ
#dropcap(
  justify: true,
  transform: letter => [#place(dx: -0.4em, sym.quote.l)#letter]
)[
  N#smallcaps[ever say never],#sym.quote.r the saying goes.
  Someday your dropcap may include leading punctuation _and_ a hanging indent.
  No worries.
  All you have to do is guess and fudge.
]
```

![image](https://github.com/EpicEricEE/typst-plugins/assets/7191192/ea4f2116-2f93-422a-b280-92a5b0a76b95)

I will probably add an overhang argument at some point to avoid the necessity of `place`.
Unfortunately, Typst can't do smartquotes if they're not part of the same sequence, so you'll have to resort to manual quotes.

> I did notice it works fine with some other punctuation

As there is no list of acceptable characters, I'm curious by what you mean by this.

**Comment by alerque** [comment]
That's some advanced foo! But it does work nicely. I've posted that work-around on [Polytype](https://polytype.dev/dropcaps/#typst) because it does accomplish the goal in Typst.

As for what to do with this package I'll leave that up to you but I'm happy to suggest things too.

From experience, LaTeX's `\lettrine{}` method of just manually passing a letter is robust but also not very automation friendly. For [SILE](https://sile-typesetter.org/) right now the base package does something similar where you just manually specify the content of the drop-cap. However for [CaSILE](https://github.com/sile-typesetter/casile) I needed something more automatic. I needed completely automated publishing without needing to manually copy-edit the content specifically for typesetting, so I came up with a smarter approach. Instead of marking up the content, I have a trigger that gets set (via the style of certain chapter and section headers) that just [automatically enables dropcaps for the following paragraph](https://github.com/sile-typesetter/casile/blob/master/packages/casile.lua#L92). In order for that to work I had to include detection of punctuation that should be included in the "character" being dropcaped.

You can see the grammar I used here: https://github.com/sile-typesetter/casile/blob/master/packages/casile.lua#L8. Note the PEG grammar here is not Unicode aware so this is picking up A-Z from ASCII plus a few letters from the Turkish alphbet avoiding multi-byte parsing issues in Lua. A Unicode aware letter parser like I assume Typst is using here would mean you just have to add some punctuation situations without worrying about what the letter itself could be.

This has worked quite well in production for English and Turkish book sources, but I don't know how it would generalize to other languages.

**Comment by EpicEricEE** [comment]
With the latest changes, there are now multiple ways to do this:

1. _Automagically_: Characters in front of the drop-cap that are part of the [open punctuation category](https://www.compart.com/en/unicode/category/Ps), and characters behind the drop-cap that are part of the [close punctuation category](https://www.compart.com/en/unicode/category/Pe) are automatically appended. Dots and "dumb quotes" are unfortunately part of the [other punctuation category](https://www.compart.com/en/unicode/category/Po), but I have added them explicitly nevertheless.
    
    ```typ
    #dropcap[“Yes,” says the package.]
    ```
2. Wrap first letters in a box: The whole box is then used as the "first letter".
    
    ```typ
    #dropcap[
      #box[“Y]es,” says the package.
    ]
    ```
3. Manually setting the "first letter": In case the automatic drop-cap isolation doesn't do what you want, you can now set it by a positional argument:
     
    ```typ
    #dropcap[“Y][es,” says the package]
    ```

As the Typst `smartquote` element still doesn't working across sequences, I would still recommend using the [typographic glyphs](https://op.europa.eu/en/web/eu-vocabularies/formex/physical-specifications/character-encoding/quotation-marks) or Typst symbols in this case:
```typ
#dropcap[“Yes,” says the package]
// or
#dropcap[#sym.quote.l;Yes,#sym.quote.r says the package]
// but not
#dropcap["Yes," says the package]
```

It doesn't look exactly the same as in the image I posted above, as the quotation mark is now included in the bounds, so the font size is decreased a bit. You can probably get close if you pass `top-edge: "cap-height"` to the dropcap function.

**Comment by alerque** [comment]
Thanks, these look like nice additions. I haven't given it a test-drive yet since I'm not familiar with setting up local packages for testing.

Will there be a patch release to the preview package repository any time soon with these modifications?

**Comment by EpicEricEE** [comment]
It's available now

**Comment by alerque** [comment]
I saw, I already updated the sample over an hour ago. Thanks!
