### ISSUE TITLE
Footnotes rendering on wrong pages

### ISSUE THREAD

**Issue by katharinathoele** [EpicEricEE/typst-plugins#6]
Hello! I am using droplet to create dropped capitals at the beginning of sections of my document. I don't want to have one every paragraph to have a dropped capital as I feel like that would clutter the page. Now I have noticed that footnotes I insert into the text only appear after the `dropcap` function has been closed. This results in footnotes appearing on the wrong pages, as shown in Figure 1:

![fig 1](https://github.com/EpicEricEE/typst-plugins/assets/117184494/4ccf0966-f6c4-43aa-bc2f-7705f16837fd)
Figure 1: Footnote on the wrong page

Corresponding MWE:
```#import "@preview/droplet:0.2.0": dropcap

#set page("a6")
#show par: set block(spacing: 0.65em)
#set par(first-line-indent: 1em)

#dropcap(
)[foo#footnote[bar] #lorem(50)

#lorem(50)

#lorem(50)
]
```

I have thought about circumventing this problem by closing the function after the first paragraph however there's two issues with that:
A) some paragraphs span multiple pages.
B) after a paragraph enclosed in a dropcap function, the paragraph spacing and first line indent do not work as I specified it should in the MWE.

The package is otherwise really good and I'd hate for this to be a blemish on it's otherwise pristine body.

Many thanks in advance

**Comment by EpicEricEE** [comment]
There is probably not much I can do here, as that's an issue in typst itself, see typst/typst#2449

**Comment by katharinathoele** [comment]
Ah, sorry to have bothered you then. Thank you regardless for the reply.
