### ISSUE TITLE
Equate: Make breakable equations a toggle

### ISSUE THREAD

**Issue by Enivex** [EpicEricEE/typst-plugins#7]
I'm not a fan of breakable display equations in general, because it can quickly lead to reduced readability if a line ends up on the wrong page. Therefore I use `\allowdisplaybreaks` very sparingly in LaTeX.

I'd like breakable equations to be optional (and ideally off by default, like in LaTeX).

**Comment by EpicEricEE** [comment]
I added a `breakable` parameter to the `equate` function. If set to `auto` (default), it will get the `block.breakable` value from the current context, so you can also do `show math.equation: set block(breakable: false)`. As `block.breakable` defaults to true, equations are also still breakable by default.
