### ISSUE TITLE
equate: number by heading

### ISSUE THREAD

**Issue by AstaSchnee** [EpicEricEE/typst-plugins#8]
I need _equate_ to number multiple-line equations. At the same time, I want to number the equations such that the heading numbering appears. Such as

- section 1
  + equation 1 ......(1.1)
  + equation 2 ......(1.2)
- section 2
  + equation 3 ......(2.1)

Usually, I use the package _i-figured_ to achieve it. However, the two packages seem not compatible. Is it possible for _equate_ to accomplish this at the same time? Many thanks.

**Comment by EpicEricEE** [comment]
As of Typst 0.11, you don't really need the i-figured package anymore, as it has become much simpler to do what it does:

```typ
#import "@preview/equate:0.1.0": equate

#set heading(numbering: "1.1")

// Reset counters on first-level headings.
#show heading.where(level: 1): it => {
  counter(figure.where(kind: image)).update(0)
  counter(figure.where(kind: table)).update(0)
  counter(figure.where(kind: raw)).update(0)
  counter(math.equation).update(0)
  it
}

// Set numbering to include current section number.
#set figure(numbering: (..nums) => {
  numbering("1.1", counter(heading).get().first(), ..nums)
})
#set math.equation(numbering: (..nums) => {
  numbering("(1.1)", counter(heading).get().first(), ..nums)
})

#show: equate

...
```

**Comment by AstaSchnee** [comment]
I appreciate your quick response and the detailed explanation. It solved my problem completely. Thanks again!
